---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fahs5592/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R dashboard $DEPLOYPATH
    - /bin/cp -R data $DEPLOYPATH
    - /bin/cp -R Resource $DEPLOYPATH 2>/dev/null || true
    - /bin/cp academic.html $DEPLOYPATH
    - /bin/cp experience.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp project.html $DEPLOYPATH
    - /bin/cp skill.html $DEPLOYPATH
